name: Django CI and Deploy to Render

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Vérifier la syntaxe Django
      - name: Check Django syntax
        run: |
          python manage.py check

      # Étape 5 : Construire l'image Docker
      - name: Build Docker image
        run: docker build -t course-service .

      # Étape 6 : Déployer sur Render
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-d4nfacuuk2gs739qd74g
          api-key:rnd_RLt3Kao1U2CwlV2YFBtOzottVWRe 